mindmap
  root((Administrateur))
    Voit
      les eleves voient a chaque fois l emploi du temps.
    Entend
      Veuillez vérifier les horaires pour éviter les conflits.
    Dit
      Je veux une outil pour ajoutez ou modifiez facilement un emploi du temps pour chaque enseignant
    Fait
      Afficher les emplois sur le mure.